// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blogs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlogsAdmin = `-- name: CountBlogsAdmin :one
SELECT COUNT(*)::bigint FROM blogs
WHERE (NULLIF($1, '') IS NULL OR status = $1)
  AND (cardinality($2::text[]) = 0 OR tags && $2::text[])
`

type CountBlogsAdminParams struct {
	Column1 interface{}
	Column2 []string
}

func (q *Queries) CountBlogsAdmin(ctx context.Context, arg CountBlogsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogsAdmin, arg.Column1, arg.Column2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPublishedBlogs = `-- name: CountPublishedBlogs :one
SELECT COUNT(*)::bigint FROM blogs
WHERE status = 'published'
  AND published_at IS NOT NULL
  AND (cardinality($1::text[]) = 0 OR tags && $1::text[])
`

func (q *Queries) CountPublishedBlogs(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedBlogs, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (
    title, slug, meta_description, body_html, cover_image, status, published_at,
    author_name, author_description, author_title, tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
RETURNING id, title, slug, meta_description, body_html, cover_image,
          status, published_at, created_at, updated_at,
          author_name, author_description, author_title, tags
`

type CreateBlogParams struct {
	Title             string
	Slug              string
	MetaDescription   *string
	BodyHtml          string
	CoverImage        *string
	Status            string
	PublishedAt       pgtype.Timestamptz
	AuthorName        *string
	AuthorDescription *string
	AuthorTitle       *string
	Tags              []string
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.Title,
		arg.Slug,
		arg.MetaDescription,
		arg.BodyHtml,
		arg.CoverImage,
		arg.Status,
		arg.PublishedAt,
		arg.AuthorName,
		arg.AuthorDescription,
		arg.AuthorTitle,
		arg.Tags,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :execrows
DELETE FROM blogs WHERE id = $1
`

func (q *Queries) DeleteBlog(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlog, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT id, title, slug, meta_description, body_html, cover_image,
       status, published_at, created_at, updated_at,
       author_name, author_description, author_title, tags
FROM blogs
WHERE id = $1
`

func (q *Queries) GetBlogByID(ctx context.Context, id string) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogByID, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT id, title, slug, meta_description, body_html, cover_image,
       status, published_at, created_at, updated_at,
       author_name, author_description, author_title, tags
FROM blogs
WHERE slug = $1
`

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogBySlug, slug)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}

const getPublishedBlogBySlug = `-- name: GetPublishedBlogBySlug :one
SELECT id, title, slug, meta_description, body_html, cover_image,
       status, published_at, created_at, updated_at,
       author_name, author_description, author_title, tags
FROM blogs
WHERE slug = $1
  AND status = 'published'
  AND published_at IS NOT NULL
`

func (q *Queries) GetPublishedBlogBySlug(ctx context.Context, slug string) (Blog, error) {
	row := q.db.QueryRow(ctx, getPublishedBlogBySlug, slug)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}

const listBlogsAdmin = `-- name: ListBlogsAdmin :many
SELECT id, title, slug, meta_description, body_html, cover_image,
       status, published_at, created_at, updated_at,
       author_name, author_description, author_title, tags
FROM blogs
WHERE (NULLIF($1, '') IS NULL OR status = $1)
  AND (cardinality($2::text[]) = 0 OR tags && $2::text[])
ORDER BY COALESCE(published_at, created_at) DESC
LIMIT $3 OFFSET $4
`

type ListBlogsAdminParams struct {
	Column1 interface{}
	Column2 []string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListBlogsAdmin(ctx context.Context, arg ListBlogsAdminParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, listBlogsAdmin,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.MetaDescription,
			&i.BodyHtml,
			&i.CoverImage,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorDescription,
			&i.AuthorTitle,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogs = `-- name: ListPublishedBlogs :many
SELECT id, title, slug, meta_description, body_html, cover_image,
       status, published_at, created_at, updated_at,
       author_name, author_description, author_title, tags
FROM blogs
WHERE status = 'published'
  AND published_at IS NOT NULL
  AND (cardinality($1::text[]) = 0 OR tags && $1::text[])
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedBlogsParams struct {
	Column1 []string
	Limit   int32
	Offset  int32
}

// filter_tags is a TEXT[] of tags to filter by. NULL or '{}' means no
// tag filter. Uses the && (overlap) operator — OR semantics: a post is
// returned if it has ANY of the requested tags. Indexed via idx_blogs_tags.
func (q *Queries) ListPublishedBlogs(ctx context.Context, arg ListPublishedBlogsParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogs, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.MetaDescription,
			&i.BodyHtml,
			&i.CoverImage,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorDescription,
			&i.AuthorTitle,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishBlog = `-- name: PublishBlog :one
UPDATE blogs
SET status = 'published',
    published_at = COALESCE(published_at, NOW()),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, slug, meta_description, body_html, cover_image,
          status, published_at, created_at, updated_at,
          author_name, author_description, author_title, tags
`

// Stamps published_at only on the first draft -> published transition.
// Re-publishing a previously published blog preserves the original timestamp.
func (q *Queries) PublishBlog(ctx context.Context, id string) (Blog, error) {
	row := q.db.QueryRow(ctx, publishBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}

const unpublishBlog = `-- name: UnpublishBlog :one
UPDATE blogs
SET status = 'draft',
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, slug, meta_description, body_html, cover_image,
          status, published_at, created_at, updated_at,
          author_name, author_description, author_title, tags
`

func (q *Queries) UnpublishBlog(ctx context.Context, id string) (Blog, error) {
	row := q.db.QueryRow(ctx, unpublishBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
SET title = $2,
    slug = $3,
    meta_description = $4,
    body_html = $5,
    cover_image = $6,
    author_name = $7,
    author_description = $8,
    author_title = $9,
    tags = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, slug, meta_description, body_html, cover_image,
          status, published_at, created_at, updated_at,
          author_name, author_description, author_title, tags
`

type UpdateBlogParams struct {
	ID                string
	Title             string
	Slug              string
	MetaDescription   *string
	BodyHtml          string
	CoverImage        *string
	AuthorName        *string
	AuthorDescription *string
	AuthorTitle       *string
	Tags              []string
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, updateBlog,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.MetaDescription,
		arg.BodyHtml,
		arg.CoverImage,
		arg.AuthorName,
		arg.AuthorDescription,
		arg.AuthorTitle,
		arg.Tags,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MetaDescription,
		&i.BodyHtml,
		&i.CoverImage,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorDescription,
		&i.AuthorTitle,
		&i.Tags,
	)
	return i, err
}
