// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveUniversityClaim = `-- name: ApproveUniversityClaim :one
UPDATE university_claims
SET status = 'approved',
    reviewer_id = $2,
    reviewed_at = NOW(),
    review_note = $3,
    created_user_id = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, university_id, full_name, work_email, role, document_url, status, reviewer_id, reviewed_at, review_note, created_user_id, created_at, updated_at
`

type ApproveUniversityClaimParams struct {
	ID            string
	ReviewerID    pgtype.UUID
	ReviewNote    *string
	CreatedUserID pgtype.UUID
}

func (q *Queries) ApproveUniversityClaim(ctx context.Context, arg ApproveUniversityClaimParams) (UniversityClaim, error) {
	row := q.db.QueryRow(ctx, approveUniversityClaim,
		arg.ID,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.CreatedUserID,
	)
	var i UniversityClaim
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPendingClaimsForUniversity = `-- name: CountPendingClaimsForUniversity :one
SELECT COUNT(*) FROM university_claims
WHERE university_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingClaimsForUniversity(ctx context.Context, universityID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingClaimsForUniversity, universityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniversityClaims = `-- name: CountUniversityClaims :one
SELECT COUNT(*) FROM university_claims
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountUniversityClaims(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countUniversityClaims, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUniversityClaim = `-- name: CreateUniversityClaim :one
INSERT INTO university_claims (university_id, full_name, work_email, role, document_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, university_id, full_name, work_email, role, document_url, status, reviewer_id, reviewed_at, review_note, created_user_id, created_at, updated_at
`

type CreateUniversityClaimParams struct {
	UniversityID string
	FullName     string
	WorkEmail    string
	Role         string
	DocumentUrl  string
}

func (q *Queries) CreateUniversityClaim(ctx context.Context, arg CreateUniversityClaimParams) (UniversityClaim, error) {
	row := q.db.QueryRow(ctx, createUniversityClaim,
		arg.UniversityID,
		arg.FullName,
		arg.WorkEmail,
		arg.Role,
		arg.DocumentUrl,
	)
	var i UniversityClaim
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUniversityClaimByID = `-- name: GetUniversityClaimByID :one
SELECT
    c.id, c.university_id, u.name AS university_name,
    c.full_name, c.work_email, c.role, c.document_url,
    c.status, c.reviewer_id, c.reviewed_at, c.review_note,
    c.created_user_id, c.created_at, c.updated_at
FROM university_claims c
JOIN universities u ON u.id = c.university_id
WHERE c.id = $1
`

type GetUniversityClaimByIDRow struct {
	ID             string
	UniversityID   string
	UniversityName string
	FullName       string
	WorkEmail      string
	Role           string
	DocumentUrl    string
	Status         string
	ReviewerID     pgtype.UUID
	ReviewedAt     pgtype.Timestamptz
	ReviewNote     *string
	CreatedUserID  pgtype.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// JOINs universities so the admin dashboard can show the university name
// alongside the claim row in a single round-trip.
func (q *Queries) GetUniversityClaimByID(ctx context.Context, id string) (GetUniversityClaimByIDRow, error) {
	row := q.db.QueryRow(ctx, getUniversityClaimByID, id)
	var i GetUniversityClaimByIDRow
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.UniversityName,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUniversityClaims = `-- name: ListUniversityClaims :many
SELECT
    c.id, c.university_id, u.name AS university_name,
    c.full_name, c.work_email, c.role, c.document_url,
    c.status, c.reviewer_id, c.reviewed_at, c.review_note,
    c.created_user_id, c.created_at, c.updated_at
FROM university_claims c
JOIN universities u ON u.id = c.university_id
WHERE ($1::text = '' OR c.status = $1)
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUniversityClaimsParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListUniversityClaimsRow struct {
	ID             string
	UniversityID   string
	UniversityName string
	FullName       string
	WorkEmail      string
	Role           string
	DocumentUrl    string
	Status         string
	ReviewerID     pgtype.UUID
	ReviewedAt     pgtype.Timestamptz
	ReviewNote     *string
	CreatedUserID  pgtype.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListUniversityClaims(ctx context.Context, arg ListUniversityClaimsParams) ([]ListUniversityClaimsRow, error) {
	rows, err := q.db.Query(ctx, listUniversityClaims, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUniversityClaimsRow{}
	for rows.Next() {
		var i ListUniversityClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.UniversityID,
			&i.UniversityName,
			&i.FullName,
			&i.WorkEmail,
			&i.Role,
			&i.DocumentUrl,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.CreatedUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectUniversityClaim = `-- name: RejectUniversityClaim :one
UPDATE university_claims
SET status = 'rejected',
    reviewer_id = $2,
    reviewed_at = NOW(),
    review_note = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, university_id, full_name, work_email, role, document_url, status, reviewer_id, reviewed_at, review_note, created_user_id, created_at, updated_at
`

type RejectUniversityClaimParams struct {
	ID         string
	ReviewerID pgtype.UUID
	ReviewNote *string
}

func (q *Queries) RejectUniversityClaim(ctx context.Context, arg RejectUniversityClaimParams) (UniversityClaim, error) {
	row := q.db.QueryRow(ctx, rejectUniversityClaim, arg.ID, arg.ReviewerID, arg.ReviewNote)
	var i UniversityClaim
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
