// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: colleges.sql

package sqlc

import (
	"context"
)

const countCollegesByUniversity = `-- name: CountCollegesByUniversity :one
SELECT COUNT(*) FROM colleges WHERE university_id = $1
`

func (q *Queries) CountCollegesByUniversity(ctx context.Context, universityID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCollegesByUniversity, universityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollege = `-- name: CreateCollege :one
INSERT INTO colleges (
    name, slug, university_id, overview, excerpt,
    country, state, city, full_location,
    cover_image, logo, institution_type, campus_setting,
    contact_email, contact_phone, website, zipcode,
    founded_year, campus_size, gallery_images,
    is_popular, is_featured
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22
)
RETURNING
    id, name, slug, university_id, overview, excerpt,
    country, state, city, full_location,
    cover_image, logo, institution_type, campus_setting,
    contact_email, contact_phone, website, zipcode,
    founded_year, campus_size, gallery_images,
    is_popular, is_featured, created_at, updated_at
`

type CreateCollegeParams struct {
	Name            string
	Slug            string
	UniversityID    string
	Overview        string
	Excerpt         *string
	Country         *string
	State           *string
	City            *string
	FullLocation    *string
	CoverImage      *string
	Logo            *string
	InstitutionType *string
	CampusSetting   *string
	ContactEmail    *string
	ContactPhone    *string
	Website         *string
	Zipcode         *string
	FoundedYear     *int16
	CampusSize      *string
	GalleryImages   []string
	IsPopular       bool
	IsFeatured      bool
}

func (q *Queries) CreateCollege(ctx context.Context, arg CreateCollegeParams) (College, error) {
	row := q.db.QueryRow(ctx, createCollege,
		arg.Name,
		arg.Slug,
		arg.UniversityID,
		arg.Overview,
		arg.Excerpt,
		arg.Country,
		arg.State,
		arg.City,
		arg.FullLocation,
		arg.CoverImage,
		arg.Logo,
		arg.InstitutionType,
		arg.CampusSetting,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Website,
		arg.Zipcode,
		arg.FoundedYear,
		arg.CampusSize,
		arg.GalleryImages,
		arg.IsPopular,
		arg.IsFeatured,
	)
	var i College
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.UniversityID,
		&i.Overview,
		&i.Excerpt,
		&i.Country,
		&i.State,
		&i.City,
		&i.FullLocation,
		&i.CoverImage,
		&i.Logo,
		&i.InstitutionType,
		&i.CampusSetting,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Website,
		&i.Zipcode,
		&i.FoundedYear,
		&i.CampusSize,
		&i.GalleryImages,
		&i.IsPopular,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollegeByID = `-- name: GetCollegeByID :one
SELECT
    id, name, slug, university_id, overview, excerpt,
    country, state, city, full_location,
    cover_image, logo, institution_type, campus_setting,
    contact_email, contact_phone, website, zipcode,
    founded_year, campus_size, gallery_images,
    is_popular, is_featured, created_at, updated_at
FROM colleges
WHERE id = $1
`

func (q *Queries) GetCollegeByID(ctx context.Context, id string) (College, error) {
	row := q.db.QueryRow(ctx, getCollegeByID, id)
	var i College
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.UniversityID,
		&i.Overview,
		&i.Excerpt,
		&i.Country,
		&i.State,
		&i.City,
		&i.FullLocation,
		&i.CoverImage,
		&i.Logo,
		&i.InstitutionType,
		&i.CampusSetting,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Website,
		&i.Zipcode,
		&i.FoundedYear,
		&i.CampusSize,
		&i.GalleryImages,
		&i.IsPopular,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollegesByUniversity = `-- name: ListCollegesByUniversity :many
SELECT
    id, name, slug, university_id, overview, excerpt,
    country, state, city, full_location,
    cover_image, logo, institution_type, campus_setting,
    contact_email, contact_phone, website, zipcode,
    founded_year, campus_size, gallery_images,
    is_popular, is_featured, created_at, updated_at
FROM colleges
WHERE university_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListCollegesByUniversityParams struct {
	UniversityID string
	Limit        int32
	Offset       int32
}

func (q *Queries) ListCollegesByUniversity(ctx context.Context, arg ListCollegesByUniversityParams) ([]College, error) {
	rows, err := q.db.Query(ctx, listCollegesByUniversity, arg.UniversityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []College{}
	for rows.Next() {
		var i College
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.UniversityID,
			&i.Overview,
			&i.Excerpt,
			&i.Country,
			&i.State,
			&i.City,
			&i.FullLocation,
			&i.CoverImage,
			&i.Logo,
			&i.InstitutionType,
			&i.CampusSetting,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Website,
			&i.Zipcode,
			&i.FoundedYear,
			&i.CampusSize,
			&i.GalleryImages,
			&i.IsPopular,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepresentedCollegeIDs = `-- name: ListRepresentedCollegeIDs :many
SELECT c.id
FROM colleges c
JOIN users u ON u.representative_college_id = c.id
WHERE c.id = ANY($1::uuid[])
`

func (q *Queries) ListRepresentedCollegeIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRepresentedCollegeIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchColleges = `-- name: SearchColleges :many
SELECT
    c.id,
    c.name,
    c.slug,
    u.id AS university_id,
    u.name AS university_name,
    u.slug AS university_slug,
    COALESCE(u.logo, '') AS university_logo,
    COALESCE(c.country, '') AS country,
    COALESCE(c.state, '') AS state,
    COALESCE(c.city, '') AS city,
    COALESCE(c.full_location, '') AS full_location,
    COALESCE(c.logo, '') AS logo
FROM colleges c
JOIN universities u ON u.id = c.university_id
WHERE similarity(c.name, $1) > 0.2
   OR similarity(c.full_location, $1) > 0.2
   OR similarity(c.city, $1) > 0.2
   OR similarity(c.state, $1) > 0.2
   OR similarity(c.country, $1) > 0.2
   OR similarity(u.name, $1) > 0.2
   OR similarity(u.slug, $1) > 0.2
ORDER BY GREATEST(
    similarity(c.name, $1),
    similarity(c.full_location, $1),
    similarity(c.city, $1),
    similarity(u.name, $1),
    similarity(u.slug, $1)
) DESC, c.name ASC
LIMIT $2
`

type SearchCollegesParams struct {
	Similarity string
	Limit      int32
}

type SearchCollegesRow struct {
	ID             string
	Name           string
	Slug           string
	UniversityID   string
	UniversityName string
	UniversitySlug string
	UniversityLogo string
	Country        string
	State          string
	City           string
	FullLocation   string
	Logo           string
}

// Typo-tolerant search across college + parent-university fields via pg_trgm.
// JOIN is INNER because college.university_id has ON DELETE RESTRICT and is
// NOT NULL — every college has exactly one parent university. SELECT re-aliases
// `u.id AS university_id` so the API response carries the university id once
// (it equals college.university_id, but reading u.id keeps the join honest).
// COALESCE keeps nullable columns as plain strings in the row type.
func (q *Queries) SearchColleges(ctx context.Context, arg SearchCollegesParams) ([]SearchCollegesRow, error) {
	rows, err := q.db.Query(ctx, searchColleges, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCollegesRow{}
	for rows.Next() {
		var i SearchCollegesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.UniversityID,
			&i.UniversityName,
			&i.UniversitySlug,
			&i.UniversityLogo,
			&i.Country,
			&i.State,
			&i.City,
			&i.FullLocation,
			&i.Logo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
