// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: college_claims.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveCollegeClaim = `-- name: ApproveCollegeClaim :one
UPDATE college_claims
SET status = 'approved',
    reviewer_id = $2,
    reviewed_at = NOW(),
    review_note = $3,
    created_user_id = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, college_id, full_name, work_email, role, document_url, status, reviewer_id, reviewed_at, review_note, created_user_id, created_at, updated_at
`

type ApproveCollegeClaimParams struct {
	ID            string
	ReviewerID    pgtype.UUID
	ReviewNote    *string
	CreatedUserID pgtype.UUID
}

func (q *Queries) ApproveCollegeClaim(ctx context.Context, arg ApproveCollegeClaimParams) (CollegeClaim, error) {
	row := q.db.QueryRow(ctx, approveCollegeClaim,
		arg.ID,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.CreatedUserID,
	)
	var i CollegeClaim
	err := row.Scan(
		&i.ID,
		&i.CollegeID,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCollegeClaims = `-- name: CountCollegeClaims :one
SELECT COUNT(*) FROM college_claims
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountCollegeClaims(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countCollegeClaims, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingClaimsForCollege = `-- name: CountPendingClaimsForCollege :one
SELECT COUNT(*) FROM college_claims
WHERE college_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingClaimsForCollege(ctx context.Context, collegeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingClaimsForCollege, collegeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollegeClaim = `-- name: CreateCollegeClaim :one
INSERT INTO college_claims (college_id, full_name, work_email, role, document_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, college_id, full_name, work_email, role, document_url, status, reviewer_id, reviewed_at, review_note, created_user_id, created_at, updated_at
`

type CreateCollegeClaimParams struct {
	CollegeID   string
	FullName    string
	WorkEmail   string
	Role        string
	DocumentUrl string
}

func (q *Queries) CreateCollegeClaim(ctx context.Context, arg CreateCollegeClaimParams) (CollegeClaim, error) {
	row := q.db.QueryRow(ctx, createCollegeClaim,
		arg.CollegeID,
		arg.FullName,
		arg.WorkEmail,
		arg.Role,
		arg.DocumentUrl,
	)
	var i CollegeClaim
	err := row.Scan(
		&i.ID,
		&i.CollegeID,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollegeClaimByID = `-- name: GetCollegeClaimByID :one
SELECT
    c.id, c.college_id, co.name AS college_name,
    c.full_name, c.work_email, c.role, c.document_url,
    c.status, c.reviewer_id, c.reviewed_at, c.review_note,
    c.created_user_id, c.created_at, c.updated_at
FROM college_claims c
JOIN colleges co ON co.id = c.college_id
WHERE c.id = $1
`

type GetCollegeClaimByIDRow struct {
	ID            string
	CollegeID     string
	CollegeName   string
	FullName      string
	WorkEmail     string
	Role          string
	DocumentUrl   string
	Status        string
	ReviewerID    pgtype.UUID
	ReviewedAt    pgtype.Timestamptz
	ReviewNote    *string
	CreatedUserID pgtype.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// JOINs colleges so the admin dashboard can show the college name
// alongside the claim row in a single round-trip.
func (q *Queries) GetCollegeClaimByID(ctx context.Context, id string) (GetCollegeClaimByIDRow, error) {
	row := q.db.QueryRow(ctx, getCollegeClaimByID, id)
	var i GetCollegeClaimByIDRow
	err := row.Scan(
		&i.ID,
		&i.CollegeID,
		&i.CollegeName,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollegeClaims = `-- name: ListCollegeClaims :many
SELECT
    c.id, c.college_id, co.name AS college_name,
    c.full_name, c.work_email, c.role, c.document_url,
    c.status, c.reviewer_id, c.reviewed_at, c.review_note,
    c.created_user_id, c.created_at, c.updated_at
FROM college_claims c
JOIN colleges co ON co.id = c.college_id
WHERE ($1::text IS NULL OR c.status = $1)
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCollegeClaimsParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListCollegeClaimsRow struct {
	ID            string
	CollegeID     string
	CollegeName   string
	FullName      string
	WorkEmail     string
	Role          string
	DocumentUrl   string
	Status        string
	ReviewerID    pgtype.UUID
	ReviewedAt    pgtype.Timestamptz
	ReviewNote    *string
	CreatedUserID pgtype.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListCollegeClaims(ctx context.Context, arg ListCollegeClaimsParams) ([]ListCollegeClaimsRow, error) {
	rows, err := q.db.Query(ctx, listCollegeClaims, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollegeClaimsRow{}
	for rows.Next() {
		var i ListCollegeClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.CollegeID,
			&i.CollegeName,
			&i.FullName,
			&i.WorkEmail,
			&i.Role,
			&i.DocumentUrl,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.CreatedUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectCollegeClaim = `-- name: RejectCollegeClaim :one
UPDATE college_claims
SET status = 'rejected',
    reviewer_id = $2,
    reviewed_at = NOW(),
    review_note = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, college_id, full_name, work_email, role, document_url, status, reviewer_id, reviewed_at, review_note, created_user_id, created_at, updated_at
`

type RejectCollegeClaimParams struct {
	ID         string
	ReviewerID pgtype.UUID
	ReviewNote *string
}

func (q *Queries) RejectCollegeClaim(ctx context.Context, arg RejectCollegeClaimParams) (CollegeClaim, error) {
	row := q.db.QueryRow(ctx, rejectCollegeClaim, arg.ID, arg.ReviewerID, arg.ReviewNote)
	var i CollegeClaim
	err := row.Scan(
		&i.ID,
		&i.CollegeID,
		&i.FullName,
		&i.WorkEmail,
		&i.Role,
		&i.DocumentUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
