// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counselling.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCounsellingInquiries = `-- name: CountCounsellingInquiries :one
SELECT COUNT(*) FROM counselling_inquiries
WHERE (NULLIF($1, '') IS NULL OR status = $1)
  AND (
        (NULLIF($2, '') IS NULL)
     OR ($2 = '__general__' AND target_type IS NULL)
     OR ($2 <> '__general__' AND target_type = $2
            AND (NULLIF($3, '') IS NULL OR target_id::text = $3))
  )
`

type CountCounsellingInquiriesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

// Filter contract for the target dimension ($2, $3):
//
//	$2 NULL or ''                        → no target filter, match anything
//	$2 = '__general__'                   → only general rows (target_type IS NULL)
//	$2 = 'university' | 'college'        → match that target_type, optionally
//	                                       narrowed by target_id ($3)
//
// We use NULLIF on $2 and $3 because sqlc hands us string params and Go's
// empty string ("") is not the same as SQL NULL — without NULLIF the "no
// filter" case would compare target_type to ” and match nothing.
func (q *Queries) CountCounsellingInquiries(ctx context.Context, arg CountCounsellingInquiriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCounsellingInquiries, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCounsellingInquiry = `-- name: CreateCounsellingInquiry :one
INSERT INTO counselling_inquiries (
    target_type, target_id, full_name, email, phone, country,
    preferred_university, program_of_interest, start_term,
    current_education, test_scores, message, resume_url
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13
)
RETURNING id, target_type, target_id, full_name, email, phone, country, preferred_university, program_of_interest, start_term, current_education, test_scores, message, resume_url, status, reviewer_id, reviewed_at, review_note, created_at, updated_at
`

type CreateCounsellingInquiryParams struct {
	TargetType          *string
	TargetID            pgtype.UUID
	FullName            string
	Email               string
	Phone               *string
	Country             *string
	PreferredUniversity *string
	ProgramOfInterest   *string
	StartTerm           *string
	CurrentEducation    *string
	TestScores          *string
	Message             *string
	ResumeUrl           *string
}

func (q *Queries) CreateCounsellingInquiry(ctx context.Context, arg CreateCounsellingInquiryParams) (CounsellingInquiry, error) {
	row := q.db.QueryRow(ctx, createCounsellingInquiry,
		arg.TargetType,
		arg.TargetID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.PreferredUniversity,
		arg.ProgramOfInterest,
		arg.StartTerm,
		arg.CurrentEducation,
		arg.TestScores,
		arg.Message,
		arg.ResumeUrl,
	)
	var i CounsellingInquiry
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.PreferredUniversity,
		&i.ProgramOfInterest,
		&i.StartTerm,
		&i.CurrentEducation,
		&i.TestScores,
		&i.Message,
		&i.ResumeUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCounsellingInquiryByID = `-- name: GetCounsellingInquiryByID :one
SELECT
    ci.id, ci.target_type, ci.target_id, ci.full_name, ci.email,
    ci.phone, ci.country, ci.preferred_university,
    ci.program_of_interest, ci.start_term, ci.current_education,
    ci.test_scores, ci.message, ci.resume_url,
    ci.status, ci.reviewer_id, ci.reviewed_at, ci.review_note,
    ci.created_at, ci.updated_at,
    COALESCE(u.name, co.name, '') AS target_name
FROM counselling_inquiries ci
LEFT JOIN universities u
    ON ci.target_type = 'university' AND u.id = ci.target_id
LEFT JOIN colleges co
    ON ci.target_type = 'college' AND co.id = ci.target_id
WHERE ci.id = $1
`

type GetCounsellingInquiryByIDRow struct {
	ID                  string
	TargetType          *string
	TargetID            pgtype.UUID
	FullName            string
	Email               string
	Phone               *string
	Country             *string
	PreferredUniversity *string
	ProgramOfInterest   *string
	StartTerm           *string
	CurrentEducation    *string
	TestScores          *string
	Message             *string
	ResumeUrl           *string
	Status              string
	ReviewerID          pgtype.UUID
	ReviewedAt          pgtype.Timestamptz
	ReviewNote          *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	TargetName          string
}

// NULL-safe LEFT JOINs produce a single row regardless of which (if any)
// target table the row points at. target_name is populated only when
// target_type is set; the service maps NULL into an empty string.
func (q *Queries) GetCounsellingInquiryByID(ctx context.Context, id string) (GetCounsellingInquiryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCounsellingInquiryByID, id)
	var i GetCounsellingInquiryByIDRow
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.PreferredUniversity,
		&i.ProgramOfInterest,
		&i.StartTerm,
		&i.CurrentEducation,
		&i.TestScores,
		&i.Message,
		&i.ResumeUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetName,
	)
	return i, err
}

const listCounsellingInquiries = `-- name: ListCounsellingInquiries :many
SELECT
    ci.id, ci.target_type, ci.target_id, ci.full_name, ci.email,
    ci.phone, ci.country, ci.preferred_university,
    ci.program_of_interest, ci.start_term, ci.current_education,
    ci.test_scores, ci.message, ci.resume_url,
    ci.status, ci.reviewer_id, ci.reviewed_at, ci.review_note,
    ci.created_at, ci.updated_at,
    COALESCE(u.name, co.name, '') AS target_name
FROM counselling_inquiries ci
LEFT JOIN universities u
    ON ci.target_type = 'university' AND u.id = ci.target_id
LEFT JOIN colleges co
    ON ci.target_type = 'college' AND co.id = ci.target_id
WHERE (NULLIF($1, '') IS NULL OR ci.status = $1)
  AND (
        (NULLIF($2, '') IS NULL)
     OR ($2 = '__general__' AND ci.target_type IS NULL)
     OR ($2 <> '__general__' AND ci.target_type = $2
            AND (NULLIF($3, '') IS NULL OR ci.target_id::text = $3))
  )
ORDER BY ci.created_at DESC
LIMIT $4 OFFSET $5
`

type ListCounsellingInquiriesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Limit   int32
	Offset  int32
}

type ListCounsellingInquiriesRow struct {
	ID                  string
	TargetType          *string
	TargetID            pgtype.UUID
	FullName            string
	Email               string
	Phone               *string
	Country             *string
	PreferredUniversity *string
	ProgramOfInterest   *string
	StartTerm           *string
	CurrentEducation    *string
	TestScores          *string
	Message             *string
	ResumeUrl           *string
	Status              string
	ReviewerID          pgtype.UUID
	ReviewedAt          pgtype.Timestamptz
	ReviewNote          *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	TargetName          string
}

// Same filter contract as CountCounsellingInquiries; see comment there.
func (q *Queries) ListCounsellingInquiries(ctx context.Context, arg ListCounsellingInquiriesParams) ([]ListCounsellingInquiriesRow, error) {
	rows, err := q.db.Query(ctx, listCounsellingInquiries,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounsellingInquiriesRow{}
	for rows.Next() {
		var i ListCounsellingInquiriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.PreferredUniversity,
			&i.ProgramOfInterest,
			&i.StartTerm,
			&i.CurrentEducation,
			&i.TestScores,
			&i.Message,
			&i.ResumeUrl,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounsellingStatus = `-- name: UpdateCounsellingStatus :one
UPDATE counselling_inquiries
SET status = $2,
    reviewer_id = $3,
    reviewed_at = $4,
    review_note = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, target_type, target_id, full_name, email, phone, country, preferred_university, program_of_interest, start_term, current_education, test_scores, message, resume_url, status, reviewer_id, reviewed_at, review_note, created_at, updated_at
`

type UpdateCounsellingStatusParams struct {
	ID         string
	Status     string
	ReviewerID pgtype.UUID
	ReviewedAt pgtype.Timestamptz
	ReviewNote *string
}

// Sets status + reviewer stamp + note in one shot. The service decides
// whether to set reviewed_at (= NOW() when transitioning to reviewed,
// stays NULL for archived if the row was never reviewed, etc.).
func (q *Queries) UpdateCounsellingStatus(ctx context.Context, arg UpdateCounsellingStatusParams) (CounsellingInquiry, error) {
	row := q.db.QueryRow(ctx, updateCounsellingStatus,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewedAt,
		arg.ReviewNote,
	)
	var i CounsellingInquiry
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.PreferredUniversity,
		&i.ProgramOfInterest,
		&i.StartTerm,
		&i.CurrentEducation,
		&i.TestScores,
		&i.Message,
		&i.ResumeUrl,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
