// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"
)

const addCollegeFavorite = `-- name: AddCollegeFavorite :exec
INSERT INTO college_favorites (user_id, college_id)
VALUES ($1, $2)
ON CONFLICT (user_id, college_id) DO NOTHING
`

type AddCollegeFavoriteParams struct {
	UserID    string
	CollegeID string
}

func (q *Queries) AddCollegeFavorite(ctx context.Context, arg AddCollegeFavoriteParams) error {
	_, err := q.db.Exec(ctx, addCollegeFavorite, arg.UserID, arg.CollegeID)
	return err
}

const addUniversityFavorite = `-- name: AddUniversityFavorite :exec
INSERT INTO university_favorites (user_id, university_id)
VALUES ($1, $2)
ON CONFLICT (user_id, university_id) DO NOTHING
`

type AddUniversityFavoriteParams struct {
	UserID       string
	UniversityID string
}

func (q *Queries) AddUniversityFavorite(ctx context.Context, arg AddUniversityFavoriteParams) error {
	_, err := q.db.Exec(ctx, addUniversityFavorite, arg.UserID, arg.UniversityID)
	return err
}

const countFavoritedColleges = `-- name: CountFavoritedColleges :one
SELECT COUNT(*) FROM college_favorites WHERE user_id = $1
`

func (q *Queries) CountFavoritedColleges(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritedColleges, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFavoritedUniversities = `-- name: CountFavoritedUniversities :one
SELECT COUNT(*) FROM university_favorites WHERE user_id = $1
`

func (q *Queries) CountFavoritedUniversities(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritedUniversities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listFavoritedCollegeIDs = `-- name: ListFavoritedCollegeIDs :many
SELECT college_id FROM college_favorites
WHERE user_id = $1 AND college_id = ANY($2::uuid[])
`

type ListFavoritedCollegeIDsParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) ListFavoritedCollegeIDs(ctx context.Context, arg ListFavoritedCollegeIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listFavoritedCollegeIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var college_id string
		if err := rows.Scan(&college_id); err != nil {
			return nil, err
		}
		items = append(items, college_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritedUniversityIDs = `-- name: ListFavoritedUniversityIDs :many
SELECT university_id FROM university_favorites
WHERE user_id = $1 AND university_id = ANY($2::uuid[])
`

type ListFavoritedUniversityIDsParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) ListFavoritedUniversityIDs(ctx context.Context, arg ListFavoritedUniversityIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listFavoritedUniversityIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var university_id string
		if err := rows.Scan(&university_id); err != nil {
			return nil, err
		}
		items = append(items, university_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollegeFavorite = `-- name: RemoveCollegeFavorite :exec
DELETE FROM college_favorites WHERE user_id = $1 AND college_id = $2
`

type RemoveCollegeFavoriteParams struct {
	UserID    string
	CollegeID string
}

func (q *Queries) RemoveCollegeFavorite(ctx context.Context, arg RemoveCollegeFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeCollegeFavorite, arg.UserID, arg.CollegeID)
	return err
}

const removeUniversityFavorite = `-- name: RemoveUniversityFavorite :exec
DELETE FROM university_favorites WHERE user_id = $1 AND university_id = $2
`

type RemoveUniversityFavoriteParams struct {
	UserID       string
	UniversityID string
}

func (q *Queries) RemoveUniversityFavorite(ctx context.Context, arg RemoveUniversityFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeUniversityFavorite, arg.UserID, arg.UniversityID)
	return err
}
