// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Athletic struct {
	ID   string
	Name string
}

type College struct {
	ID              string
	Name            string
	Slug            string
	UniversityID    string
	Overview        string
	Excerpt         *string
	Country         *string
	State           *string
	City            *string
	FullLocation    *string
	CoverImage      *string
	Logo            *string
	InstitutionType *string
	CampusSetting   *string
	ContactEmail    *string
	ContactPhone    *string
	Website         *string
	Zipcode         *string
	FoundedYear     *int16
	CampusSize      *string
	GalleryImages   []string
	IsPopular       bool
	IsFeatured      bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CollegeClaim struct {
	ID            string
	CollegeID     string
	FullName      string
	WorkEmail     string
	Role          string
	DocumentUrl   string
	Status        string
	ReviewerID    pgtype.UUID
	ReviewedAt    pgtype.Timestamptz
	ReviewNote    *string
	CreatedUserID pgtype.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type CollegeFavorite struct {
	UserID    string
	CollegeID string
	CreatedAt time.Time
}

type CounsellingInquiry struct {
	ID                  string
	TargetType          *string
	TargetID            pgtype.UUID
	FullName            string
	Email               string
	Phone               *string
	Country             *string
	PreferredUniversity *string
	ProgramOfInterest   *string
	StartTerm           *string
	CurrentEducation    *string
	TestScores          *string
	Message             *string
	ResumeUrl           *string
	Status              string
	ReviewerID          pgtype.UUID
	ReviewedAt          pgtype.Timestamptz
	ReviewNote          *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type DegreeLevel struct {
	ID   string
	Name string
}

type Major struct {
	ID   string
	Name string
}

type RefreshToken struct {
	ID        string
	Token     string
	UserID    string
	UserAgent *string
	ExpiresAt time.Time
	CreatedAt time.Time
	Revoked   bool
}

type SchemaMigration struct {
	Version string
}

type SpecialAffiliation struct {
	ID   string
	Name string
}

type StudyFormat struct {
	ID   string
	Name string
}

type SupportService struct {
	ID   string
	Name string
}

type University struct {
	ID                       string
	Name                     string
	Slug                     string
	Overview                 *string
	Excerpt                  *string
	Country                  *string
	State                    *string
	City                     *string
	FullLocation             *string
	CoverImage               *string
	Logo                     *string
	InstitutionType          *string
	CampusSetting            *string
	InStateTuition           pgtype.Numeric
	OutOfStateTuition        pgtype.Numeric
	InternationalTuition     pgtype.Numeric
	NeedBasedAid             bool
	MeritScholarships        bool
	WorkStudy                bool
	NoApplicationFee         bool
	AcceptanceRate           pgtype.Numeric
	TestingPolicy            *string
	SatRange                 *string
	ActRange                 *string
	OnCampusHousing          bool
	FreshmenRequiredOnCampus bool
	ContactEmail             *string
	ContactPhone             *string
	Website                  *string
	Zipcode                  *string
	TuitionMin               *int32
	TuitionMax               *int32
	AvgHighSchoolGpa         pgtype.Numeric
	FoundedYear              *int16
	CampusSize               *string
	GalleryImages            []string
	IsPopular                bool
	IsFeatured               bool
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type UniversityAthletic struct {
	UniversityID string
	AthleticID   string
}

type UniversityClaim struct {
	ID            string
	UniversityID  string
	FullName      string
	WorkEmail     string
	Role          string
	DocumentUrl   string
	Status        string
	ReviewerID    pgtype.UUID
	ReviewedAt    pgtype.Timestamptz
	ReviewNote    *string
	CreatedUserID pgtype.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UniversityDegreeLevel struct {
	UniversityID  string
	DegreeLevelID string
}

type UniversityFavorite struct {
	UserID       string
	UniversityID string
	CreatedAt    time.Time
}

type UniversityMajor struct {
	UniversityID string
	MajorID      string
}

type UniversitySpecialAffiliation struct {
	UniversityID         string
	SpecialAffiliationID string
}

type UniversityStudyFormat struct {
	UniversityID  string
	StudyFormatID string
}

type UniversitySupportService struct {
	UniversityID     string
	SupportServiceID string
}

type User struct {
	ID                         string
	FullName                   string
	Avatar                     *string
	Email                      string
	Password                   *string
	Provider                   *string
	ProviderID                 *string
	EmailVerified              bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	Role                       string
	RepresentativeUniversityID pgtype.UUID
	RepresentativeCollegeID    pgtype.UUID
}
