// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: programs.sql

package sqlc

import (
	"context"
)

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*) FROM programs
`

func (q *Queries) CountPrograms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPrograms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgramsByDegree = `-- name: CountProgramsByDegree :one
SELECT COUNT(*) FROM programs WHERE degree_id = $1
`

func (q *Queries) CountProgramsByDegree(ctx context.Context, degreeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProgramsByDegree, degreeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (title, description, excerpt, career_options, degree_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, degree_id, created_at, updated_at, excerpt, career_options
`

type CreateProgramParams struct {
	Title         string
	Description   string
	Excerpt       *string
	CareerOptions *string
	DegreeID      string
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.Title,
		arg.Description,
		arg.Excerpt,
		arg.CareerOptions,
		arg.DegreeID,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DegreeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Excerpt,
		&i.CareerOptions,
	)
	return i, err
}

const deleteProgram = `-- name: DeleteProgram :execrows
DELETE FROM programs WHERE id = $1
`

func (q *Queries) DeleteProgram(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgram, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, title, description, degree_id, created_at, updated_at, excerpt, career_options
FROM programs
WHERE id = $1
`

func (q *Queries) GetProgramByID(ctx context.Context, id string) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DegreeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Excerpt,
		&i.CareerOptions,
	)
	return i, err
}

const listAllPrograms = `-- name: ListAllPrograms :many
SELECT id, title, description, degree_id, created_at, updated_at, excerpt, career_options
FROM programs
ORDER BY title
`

func (q *Queries) ListAllPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listAllPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DegreeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Excerpt,
			&i.CareerOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, title, description, degree_id, created_at, updated_at, excerpt, career_options
FROM programs
ORDER BY title
LIMIT $1 OFFSET $2
`

type ListProgramsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DegreeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Excerpt,
			&i.CareerOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByDegree = `-- name: ListProgramsByDegree :many
SELECT id, title, description, degree_id, created_at, updated_at, excerpt, career_options
FROM programs
WHERE degree_id = $1
ORDER BY title
LIMIT $2 OFFSET $3
`

type ListProgramsByDegreeParams struct {
	DegreeID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListProgramsByDegree(ctx context.Context, arg ListProgramsByDegreeParams) ([]Program, error) {
	rows, err := q.db.Query(ctx, listProgramsByDegree, arg.DegreeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DegreeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Excerpt,
			&i.CareerOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE programs
SET title = $2,
    description = $3,
    excerpt = $4,
    career_options = $5,
    degree_id = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, degree_id, created_at, updated_at, excerpt, career_options
`

type UpdateProgramParams struct {
	ID            string
	Title         string
	Description   string
	Excerpt       *string
	CareerOptions *string
	DegreeID      string
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Excerpt,
		arg.CareerOptions,
		arg.DegreeID,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DegreeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Excerpt,
		&i.CareerOptions,
	)
	return i, err
}
