// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scholarships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScholarship = `-- name: CreateScholarship :one
INSERT INTO scholarships (
    title, slug, description, award_amount, award_min, award_max, logo,
    number_of_awards, is_renewable,
    min_gpa, requires_financial_need, country, state, city,
    application_open_date, application_deadline, award_notification_date,
    essay_required, essay_prompt, recommendation_letters_required,
    transcript_requirement, portfolio_required, application_url,
    provider_type, provider_name, contact_email, contact_phone, internal_notes,
    university_id, college_id,
    seo_title, seo_description,
    is_popular, is_featured, status
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35
)
RETURNING id, title, slug, description, award_amount, award_min, award_max, logo, number_of_awards, is_renewable, min_gpa, requires_financial_need, country, state, city, application_open_date, application_deadline, award_notification_date, essay_required, essay_prompt, recommendation_letters_required, transcript_requirement, portfolio_required, application_url, provider_type, provider_name, contact_email, contact_phone, internal_notes, university_id, college_id, seo_title, seo_description, is_popular, is_featured, status, published_at, created_at, updated_at
`

type CreateScholarshipParams struct {
	Title                         string
	Slug                          string
	Description                   string
	AwardAmount                   string
	AwardMin                      pgtype.Numeric
	AwardMax                      pgtype.Numeric
	Logo                          *string
	NumberOfAwards                *int32
	IsRenewable                   bool
	MinGpa                        pgtype.Numeric
	RequiresFinancialNeed         bool
	Country                       *string
	State                         *string
	City                          *string
	ApplicationOpenDate           pgtype.Timestamptz
	ApplicationDeadline           pgtype.Timestamptz
	AwardNotificationDate         pgtype.Timestamptz
	EssayRequired                 bool
	EssayPrompt                   *string
	RecommendationLettersRequired int32
	TranscriptRequirement         string
	PortfolioRequired             bool
	ApplicationUrl                *string
	ProviderType                  *string
	ProviderName                  *string
	ContactEmail                  *string
	ContactPhone                  *string
	InternalNotes                 *string
	UniversityID                  pgtype.UUID
	CollegeID                     pgtype.UUID
	SeoTitle                      *string
	SeoDescription                *string
	IsPopular                     bool
	IsFeatured                    bool
	Status                        string
}

func (q *Queries) CreateScholarship(ctx context.Context, arg CreateScholarshipParams) (Scholarship, error) {
	row := q.db.QueryRow(ctx, createScholarship,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.AwardAmount,
		arg.AwardMin,
		arg.AwardMax,
		arg.Logo,
		arg.NumberOfAwards,
		arg.IsRenewable,
		arg.MinGpa,
		arg.RequiresFinancialNeed,
		arg.Country,
		arg.State,
		arg.City,
		arg.ApplicationOpenDate,
		arg.ApplicationDeadline,
		arg.AwardNotificationDate,
		arg.EssayRequired,
		arg.EssayPrompt,
		arg.RecommendationLettersRequired,
		arg.TranscriptRequirement,
		arg.PortfolioRequired,
		arg.ApplicationUrl,
		arg.ProviderType,
		arg.ProviderName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.InternalNotes,
		arg.UniversityID,
		arg.CollegeID,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.IsPopular,
		arg.IsFeatured,
		arg.Status,
	)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AwardAmount,
		&i.AwardMin,
		&i.AwardMax,
		&i.Logo,
		&i.NumberOfAwards,
		&i.IsRenewable,
		&i.MinGpa,
		&i.RequiresFinancialNeed,
		&i.Country,
		&i.State,
		&i.City,
		&i.ApplicationOpenDate,
		&i.ApplicationDeadline,
		&i.AwardNotificationDate,
		&i.EssayRequired,
		&i.EssayPrompt,
		&i.RecommendationLettersRequired,
		&i.TranscriptRequirement,
		&i.PortfolioRequired,
		&i.ApplicationUrl,
		&i.ProviderType,
		&i.ProviderName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.InternalNotes,
		&i.UniversityID,
		&i.CollegeID,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.IsPopular,
		&i.IsFeatured,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScholarship = `-- name: DeleteScholarship :execrows
DELETE FROM scholarships WHERE id = $1
`

func (q *Queries) DeleteScholarship(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScholarship, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScholarshipDemographics = `-- name: DeleteScholarshipDemographics :exec
DELETE FROM scholarship_demographics WHERE scholarship_id = $1
`

func (q *Queries) DeleteScholarshipDemographics(ctx context.Context, scholarshipID string) error {
	_, err := q.db.Exec(ctx, deleteScholarshipDemographics, scholarshipID)
	return err
}

const deleteScholarshipEducationLevels = `-- name: DeleteScholarshipEducationLevels :exec
DELETE FROM scholarship_education_levels WHERE scholarship_id = $1
`

func (q *Queries) DeleteScholarshipEducationLevels(ctx context.Context, scholarshipID string) error {
	_, err := q.db.Exec(ctx, deleteScholarshipEducationLevels, scholarshipID)
	return err
}

const deleteScholarshipMajors = `-- name: DeleteScholarshipMajors :exec
DELETE FROM scholarship_majors WHERE scholarship_id = $1
`

func (q *Queries) DeleteScholarshipMajors(ctx context.Context, scholarshipID string) error {
	_, err := q.db.Exec(ctx, deleteScholarshipMajors, scholarshipID)
	return err
}

const getDemographics = `-- name: GetDemographics :many
SELECT id, name FROM demographics ORDER BY name
`

func (q *Queries) GetDemographics(ctx context.Context) ([]Demographic, error) {
	rows, err := q.db.Query(ctx, getDemographics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Demographic{}
	for rows.Next() {
		var i Demographic
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEducationLevels = `-- name: GetEducationLevels :many
SELECT id, name FROM education_levels ORDER BY name
`

func (q *Queries) GetEducationLevels(ctx context.Context) ([]EducationLevel, error) {
	rows, err := q.db.Query(ctx, getEducationLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EducationLevel{}
	for rows.Next() {
		var i EducationLevel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingDemographicIDs = `-- name: GetExistingDemographicIDs :many
SELECT id FROM demographics WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingDemographicIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingDemographicIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingEducationLevelIDs = `-- name: GetExistingEducationLevelIDs :many
SELECT id FROM education_levels WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingEducationLevelIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingEducationLevelIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScholarshipByID = `-- name: GetScholarshipByID :one
SELECT id, title, slug, description, award_amount, award_min, award_max, logo, number_of_awards, is_renewable, min_gpa, requires_financial_need, country, state, city, application_open_date, application_deadline, award_notification_date, essay_required, essay_prompt, recommendation_letters_required, transcript_requirement, portfolio_required, application_url, provider_type, provider_name, contact_email, contact_phone, internal_notes, university_id, college_id, seo_title, seo_description, is_popular, is_featured, status, published_at, created_at, updated_at FROM scholarships WHERE id = $1
`

func (q *Queries) GetScholarshipByID(ctx context.Context, id string) (Scholarship, error) {
	row := q.db.QueryRow(ctx, getScholarshipByID, id)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AwardAmount,
		&i.AwardMin,
		&i.AwardMax,
		&i.Logo,
		&i.NumberOfAwards,
		&i.IsRenewable,
		&i.MinGpa,
		&i.RequiresFinancialNeed,
		&i.Country,
		&i.State,
		&i.City,
		&i.ApplicationOpenDate,
		&i.ApplicationDeadline,
		&i.AwardNotificationDate,
		&i.EssayRequired,
		&i.EssayPrompt,
		&i.RecommendationLettersRequired,
		&i.TranscriptRequirement,
		&i.PortfolioRequired,
		&i.ApplicationUrl,
		&i.ProviderType,
		&i.ProviderName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.InternalNotes,
		&i.UniversityID,
		&i.CollegeID,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.IsPopular,
		&i.IsFeatured,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScholarshipDemographics = `-- name: GetScholarshipDemographics :many
SELECT d.id, d.name
FROM demographics d
JOIN scholarship_demographics sd ON d.id = sd.demographic_id
WHERE sd.scholarship_id = $1
ORDER BY d.name
`

func (q *Queries) GetScholarshipDemographics(ctx context.Context, scholarshipID string) ([]Demographic, error) {
	rows, err := q.db.Query(ctx, getScholarshipDemographics, scholarshipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Demographic{}
	for rows.Next() {
		var i Demographic
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScholarshipEducationLevels = `-- name: GetScholarshipEducationLevels :many
SELECT el.id, el.name
FROM education_levels el
JOIN scholarship_education_levels sel ON el.id = sel.education_level_id
WHERE sel.scholarship_id = $1
ORDER BY el.name
`

func (q *Queries) GetScholarshipEducationLevels(ctx context.Context, scholarshipID string) ([]EducationLevel, error) {
	rows, err := q.db.Query(ctx, getScholarshipEducationLevels, scholarshipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EducationLevel{}
	for rows.Next() {
		var i EducationLevel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScholarshipMajors = `-- name: GetScholarshipMajors :many
SELECT m.id, m.name
FROM majors m
JOIN scholarship_majors sm ON m.id = sm.major_id
WHERE sm.scholarship_id = $1
ORDER BY m.name
`

func (q *Queries) GetScholarshipMajors(ctx context.Context, scholarshipID string) ([]Major, error) {
	rows, err := q.db.Query(ctx, getScholarshipMajors, scholarshipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Major{}
	for rows.Next() {
		var i Major
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScholarshipDemographics = `-- name: InsertScholarshipDemographics :exec
INSERT INTO scholarship_demographics (scholarship_id, demographic_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (scholarship_id, demographic_id) DO NOTHING
`

type InsertScholarshipDemographicsParams struct {
	ScholarshipID string
	Column2       []string
}

func (q *Queries) InsertScholarshipDemographics(ctx context.Context, arg InsertScholarshipDemographicsParams) error {
	_, err := q.db.Exec(ctx, insertScholarshipDemographics, arg.ScholarshipID, arg.Column2)
	return err
}

const insertScholarshipEducationLevels = `-- name: InsertScholarshipEducationLevels :exec
INSERT INTO scholarship_education_levels (scholarship_id, education_level_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (scholarship_id, education_level_id) DO NOTHING
`

type InsertScholarshipEducationLevelsParams struct {
	ScholarshipID string
	Column2       []string
}

func (q *Queries) InsertScholarshipEducationLevels(ctx context.Context, arg InsertScholarshipEducationLevelsParams) error {
	_, err := q.db.Exec(ctx, insertScholarshipEducationLevels, arg.ScholarshipID, arg.Column2)
	return err
}

const insertScholarshipMajors = `-- name: InsertScholarshipMajors :exec
INSERT INTO scholarship_majors (scholarship_id, major_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (scholarship_id, major_id) DO NOTHING
`

type InsertScholarshipMajorsParams struct {
	ScholarshipID string
	Column2       []string
}

func (q *Queries) InsertScholarshipMajors(ctx context.Context, arg InsertScholarshipMajorsParams) error {
	_, err := q.db.Exec(ctx, insertScholarshipMajors, arg.ScholarshipID, arg.Column2)
	return err
}

const publishScholarship = `-- name: PublishScholarship :one
UPDATE scholarships
SET status = 'published',
    published_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, slug, description, award_amount, award_min, award_max, logo, number_of_awards, is_renewable, min_gpa, requires_financial_need, country, state, city, application_open_date, application_deadline, award_notification_date, essay_required, essay_prompt, recommendation_letters_required, transcript_requirement, portfolio_required, application_url, provider_type, provider_name, contact_email, contact_phone, internal_notes, university_id, college_id, seo_title, seo_description, is_popular, is_featured, status, published_at, created_at, updated_at
`

func (q *Queries) PublishScholarship(ctx context.Context, id string) (Scholarship, error) {
	row := q.db.QueryRow(ctx, publishScholarship, id)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AwardAmount,
		&i.AwardMin,
		&i.AwardMax,
		&i.Logo,
		&i.NumberOfAwards,
		&i.IsRenewable,
		&i.MinGpa,
		&i.RequiresFinancialNeed,
		&i.Country,
		&i.State,
		&i.City,
		&i.ApplicationOpenDate,
		&i.ApplicationDeadline,
		&i.AwardNotificationDate,
		&i.EssayRequired,
		&i.EssayPrompt,
		&i.RecommendationLettersRequired,
		&i.TranscriptRequirement,
		&i.PortfolioRequired,
		&i.ApplicationUrl,
		&i.ProviderType,
		&i.ProviderName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.InternalNotes,
		&i.UniversityID,
		&i.CollegeID,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.IsPopular,
		&i.IsFeatured,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchScholarships = `-- name: SearchScholarships :many
SELECT
    id,
    title,
    slug,
    COALESCE(provider_name, '') AS provider_name,
    COALESCE(provider_type, '') AS provider_type,
    COALESCE(logo, '') AS logo,
    award_amount
FROM scholarships
WHERE status = 'published'
  AND (title ILIKE '%' || $1 || '%' OR similarity(title, $1) > 0.2)
ORDER BY similarity(title, $1) DESC, title ASC
LIMIT $2
`

type SearchScholarshipsParams struct {
	Query       *string
	ResultLimit int32
}

type SearchScholarshipsRow struct {
	ID           string
	Title        string
	Slug         string
	ProviderName string
	ProviderType string
	Logo         string
	AwardAmount  string
}

// Search over title: a case-insensitive substring match (so a short query like
// "stem" finds "STEM Excellence Scholarship") OR typo-tolerant pg_trgm
// similarity (threshold 0.2, below the PG default of 0.3, so near-misses still
// match). Both forms are index-accelerated by the trigram GIN index on title.
// Only published rows are searchable; COALESCE keeps nullable columns as
// plain strings.
func (q *Queries) SearchScholarships(ctx context.Context, arg SearchScholarshipsParams) ([]SearchScholarshipsRow, error) {
	rows, err := q.db.Query(ctx, searchScholarships, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchScholarshipsRow{}
	for rows.Next() {
		var i SearchScholarshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ProviderName,
			&i.ProviderType,
			&i.Logo,
			&i.AwardAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
