// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_profile.sql

package sqlc

import (
	"context"
)

const addStudentProfileProgram = `-- name: AddStudentProfileProgram :exec
INSERT INTO student_profile_programs (user_id, program_id) VALUES ($1, $2)
ON CONFLICT (user_id, program_id) DO NOTHING
`

type AddStudentProfileProgramParams struct {
	UserID    string
	ProgramID string
}

func (q *Queries) AddStudentProfileProgram(ctx context.Context, arg AddStudentProfileProgramParams) error {
	_, err := q.db.Exec(ctx, addStudentProfileProgram, arg.UserID, arg.ProgramID)
	return err
}

const deleteStudentProfile = `-- name: DeleteStudentProfile :exec
DELETE FROM student_profile WHERE user_id = $1
`

func (q *Queries) DeleteStudentProfile(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteStudentProfile, userID)
	return err
}

const deleteStudentProfilePrograms = `-- name: DeleteStudentProfilePrograms :exec
DELETE FROM student_profile_programs WHERE user_id = $1
`

func (q *Queries) DeleteStudentProfilePrograms(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteStudentProfilePrograms, userID)
	return err
}

const getExistingProgramIDs = `-- name: GetExistingProgramIDs :many
SELECT id FROM programs WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingProgramIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingProgramIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentProfile = `-- name: GetStudentProfile :one
SELECT user_id, budget, intended_country, current_education, created_at, updated_at FROM student_profile WHERE user_id = $1
`

func (q *Queries) GetStudentProfile(ctx context.Context, userID string) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, getStudentProfile, userID)
	var i StudentProfile
	err := row.Scan(
		&i.UserID,
		&i.Budget,
		&i.IntendedCountry,
		&i.CurrentEducation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudentProfileProgramIDs = `-- name: ListStudentProfileProgramIDs :many
SELECT program_id FROM student_profile_programs WHERE user_id = $1
`

func (q *Queries) ListStudentProfileProgramIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listStudentProfileProgramIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var program_id string
		if err := rows.Scan(&program_id); err != nil {
			return nil, err
		}
		items = append(items, program_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudentProfile = `-- name: UpsertStudentProfile :one
INSERT INTO student_profile (user_id, budget, intended_country, current_education, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE
   SET budget           = COALESCE(EXCLUDED.budget,           student_profile.budget),
       intended_country  = COALESCE(EXCLUDED.intended_country,  student_profile.intended_country),
       current_education = COALESCE(EXCLUDED.current_education, student_profile.current_education),
       updated_at = NOW()
RETURNING user_id, budget, intended_country, current_education, created_at, updated_at
`

type UpsertStudentProfileParams struct {
	UserID           string
	Budget           *int64
	IntendedCountry  *string
	CurrentEducation *string
}

func (q *Queries) UpsertStudentProfile(ctx context.Context, arg UpsertStudentProfileParams) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, upsertStudentProfile,
		arg.UserID,
		arg.Budget,
		arg.IntendedCountry,
		arg.CurrentEducation,
	)
	var i StudentProfile
	err := row.Scan(
		&i.UserID,
		&i.Budget,
		&i.IntendedCountry,
		&i.CurrentEducation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
