// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: universities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUniversities = `-- name: CountUniversities :one
SELECT COUNT(*) FROM universities
`

func (q *Queries) CountUniversities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUniversities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUniversity = `-- name: CreateUniversity :one
INSERT INTO universities (
    name, slug, overview, excerpt,
    country, state, city, full_location,
    cover_image, logo,
    institution_type, campus_setting,
    in_state_tuition, out_of_state_tuition, international_tuition,
    need_based_aid, merit_scholarships, work_study, no_application_fee,
    acceptance_rate, testing_policy, sat_range, act_range,
    on_campus_housing, freshmen_required_on_campus,
    contact_email, contact_phone, website,
    zipcode, tuition_min, tuition_max, avg_high_school_gpa,
    founded_year, campus_size, gallery_images,
    is_popular, is_featured
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27, $28,
    $29, $30, $31, $32, $33, $34, $35, $36, $37
)
RETURNING id, name, slug, overview, excerpt, country, state, city, full_location, cover_image, logo, institution_type, campus_setting, in_state_tuition, out_of_state_tuition, international_tuition, need_based_aid, merit_scholarships, work_study, no_application_fee, acceptance_rate, testing_policy, sat_range, act_range, on_campus_housing, freshmen_required_on_campus, contact_email, contact_phone, website, zipcode, tuition_min, tuition_max, avg_high_school_gpa, founded_year, campus_size, gallery_images, is_popular, is_featured, created_at, updated_at
`

type CreateUniversityParams struct {
	Name                     string
	Slug                     string
	Overview                 *string
	Excerpt                  *string
	Country                  *string
	State                    *string
	City                     *string
	FullLocation             *string
	CoverImage               *string
	Logo                     *string
	InstitutionType          *string
	CampusSetting            *string
	InStateTuition           pgtype.Numeric
	OutOfStateTuition        pgtype.Numeric
	InternationalTuition     pgtype.Numeric
	NeedBasedAid             bool
	MeritScholarships        bool
	WorkStudy                bool
	NoApplicationFee         bool
	AcceptanceRate           pgtype.Numeric
	TestingPolicy            *string
	SatRange                 *string
	ActRange                 *string
	OnCampusHousing          bool
	FreshmenRequiredOnCampus bool
	ContactEmail             *string
	ContactPhone             *string
	Website                  *string
	Zipcode                  *string
	TuitionMin               *int32
	TuitionMax               *int32
	AvgHighSchoolGpa         pgtype.Numeric
	FoundedYear              *int16
	CampusSize               *string
	GalleryImages            []string
	IsPopular                bool
	IsFeatured               bool
}

func (q *Queries) CreateUniversity(ctx context.Context, arg CreateUniversityParams) (University, error) {
	row := q.db.QueryRow(ctx, createUniversity,
		arg.Name,
		arg.Slug,
		arg.Overview,
		arg.Excerpt,
		arg.Country,
		arg.State,
		arg.City,
		arg.FullLocation,
		arg.CoverImage,
		arg.Logo,
		arg.InstitutionType,
		arg.CampusSetting,
		arg.InStateTuition,
		arg.OutOfStateTuition,
		arg.InternationalTuition,
		arg.NeedBasedAid,
		arg.MeritScholarships,
		arg.WorkStudy,
		arg.NoApplicationFee,
		arg.AcceptanceRate,
		arg.TestingPolicy,
		arg.SatRange,
		arg.ActRange,
		arg.OnCampusHousing,
		arg.FreshmenRequiredOnCampus,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Website,
		arg.Zipcode,
		arg.TuitionMin,
		arg.TuitionMax,
		arg.AvgHighSchoolGpa,
		arg.FoundedYear,
		arg.CampusSize,
		arg.GalleryImages,
		arg.IsPopular,
		arg.IsFeatured,
	)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Overview,
		&i.Excerpt,
		&i.Country,
		&i.State,
		&i.City,
		&i.FullLocation,
		&i.CoverImage,
		&i.Logo,
		&i.InstitutionType,
		&i.CampusSetting,
		&i.InStateTuition,
		&i.OutOfStateTuition,
		&i.InternationalTuition,
		&i.NeedBasedAid,
		&i.MeritScholarships,
		&i.WorkStudy,
		&i.NoApplicationFee,
		&i.AcceptanceRate,
		&i.TestingPolicy,
		&i.SatRange,
		&i.ActRange,
		&i.OnCampusHousing,
		&i.FreshmenRequiredOnCampus,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Website,
		&i.Zipcode,
		&i.TuitionMin,
		&i.TuitionMax,
		&i.AvgHighSchoolGpa,
		&i.FoundedYear,
		&i.CampusSize,
		&i.GalleryImages,
		&i.IsPopular,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAthletics = `-- name: GetAthletics :many
SELECT id, name FROM athletics ORDER BY name
`

func (q *Queries) GetAthletics(ctx context.Context) ([]Athletic, error) {
	rows, err := q.db.Query(ctx, getAthletics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athletic{}
	for rows.Next() {
		var i Athletic
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDegreeLevels = `-- name: GetDegreeLevels :many
SELECT id, name FROM degree_levels ORDER BY name
`

func (q *Queries) GetDegreeLevels(ctx context.Context) ([]DegreeLevel, error) {
	rows, err := q.db.Query(ctx, getDegreeLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DegreeLevel{}
	for rows.Next() {
		var i DegreeLevel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingAthleticIDs = `-- name: GetExistingAthleticIDs :many
SELECT id FROM athletics WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingAthleticIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingAthleticIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingDegreeLevelIDs = `-- name: GetExistingDegreeLevelIDs :many
SELECT id FROM degree_levels WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingDegreeLevelIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingDegreeLevelIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingMajorIDs = `-- name: GetExistingMajorIDs :many
SELECT id FROM majors WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingMajorIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingMajorIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingSpecialAffiliationIDs = `-- name: GetExistingSpecialAffiliationIDs :many
SELECT id FROM special_affiliations WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingSpecialAffiliationIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingSpecialAffiliationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingStudyFormatIDs = `-- name: GetExistingStudyFormatIDs :many
SELECT id FROM study_formats WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingStudyFormatIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingStudyFormatIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingSupportServiceIDs = `-- name: GetExistingSupportServiceIDs :many
SELECT id FROM support_services WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetExistingSupportServiceIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingSupportServiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMajors = `-- name: GetMajors :many
SELECT id, name FROM majors ORDER BY name
`

func (q *Queries) GetMajors(ctx context.Context) ([]Major, error) {
	rows, err := q.db.Query(ctx, getMajors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Major{}
	for rows.Next() {
		var i Major
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecialAffiliations = `-- name: GetSpecialAffiliations :many
SELECT id, name FROM special_affiliations ORDER BY name
`

func (q *Queries) GetSpecialAffiliations(ctx context.Context) ([]SpecialAffiliation, error) {
	rows, err := q.db.Query(ctx, getSpecialAffiliations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpecialAffiliation{}
	for rows.Next() {
		var i SpecialAffiliation
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudyFormats = `-- name: GetStudyFormats :many
SELECT id, name FROM study_formats ORDER BY name
`

func (q *Queries) GetStudyFormats(ctx context.Context) ([]StudyFormat, error) {
	rows, err := q.db.Query(ctx, getStudyFormats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudyFormat{}
	for rows.Next() {
		var i StudyFormat
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupportServices = `-- name: GetSupportServices :many
SELECT id, name FROM support_services ORDER BY name
`

func (q *Queries) GetSupportServices(ctx context.Context) ([]SupportService, error) {
	rows, err := q.db.Query(ctx, getSupportServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportService{}
	for rows.Next() {
		var i SupportService
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniversityAthletics = `-- name: GetUniversityAthletics :many
SELECT a.id, a.name
FROM athletics a
JOIN university_athletics ua ON a.id = ua.athletic_id
WHERE ua.university_id = $1
ORDER BY a.name
`

func (q *Queries) GetUniversityAthletics(ctx context.Context, universityID string) ([]Athletic, error) {
	rows, err := q.db.Query(ctx, getUniversityAthletics, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athletic{}
	for rows.Next() {
		var i Athletic
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniversityByID = `-- name: GetUniversityByID :one
SELECT id, name, slug, overview, excerpt, country, state, city, full_location, cover_image, logo, institution_type, campus_setting, in_state_tuition, out_of_state_tuition, international_tuition, need_based_aid, merit_scholarships, work_study, no_application_fee, acceptance_rate, testing_policy, sat_range, act_range, on_campus_housing, freshmen_required_on_campus, contact_email, contact_phone, website, zipcode, tuition_min, tuition_max, avg_high_school_gpa, founded_year, campus_size, gallery_images, is_popular, is_featured, created_at, updated_at FROM universities WHERE id = $1
`

func (q *Queries) GetUniversityByID(ctx context.Context, id string) (University, error) {
	row := q.db.QueryRow(ctx, getUniversityByID, id)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Overview,
		&i.Excerpt,
		&i.Country,
		&i.State,
		&i.City,
		&i.FullLocation,
		&i.CoverImage,
		&i.Logo,
		&i.InstitutionType,
		&i.CampusSetting,
		&i.InStateTuition,
		&i.OutOfStateTuition,
		&i.InternationalTuition,
		&i.NeedBasedAid,
		&i.MeritScholarships,
		&i.WorkStudy,
		&i.NoApplicationFee,
		&i.AcceptanceRate,
		&i.TestingPolicy,
		&i.SatRange,
		&i.ActRange,
		&i.OnCampusHousing,
		&i.FreshmenRequiredOnCampus,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Website,
		&i.Zipcode,
		&i.TuitionMin,
		&i.TuitionMax,
		&i.AvgHighSchoolGpa,
		&i.FoundedYear,
		&i.CampusSize,
		&i.GalleryImages,
		&i.IsPopular,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUniversityDegreeLevels = `-- name: GetUniversityDegreeLevels :many
SELECT dl.id, dl.name
FROM degree_levels dl
JOIN university_degree_levels udl ON dl.id = udl.degree_level_id
WHERE udl.university_id = $1
ORDER BY dl.name
`

func (q *Queries) GetUniversityDegreeLevels(ctx context.Context, universityID string) ([]DegreeLevel, error) {
	rows, err := q.db.Query(ctx, getUniversityDegreeLevels, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DegreeLevel{}
	for rows.Next() {
		var i DegreeLevel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniversityMajors = `-- name: GetUniversityMajors :many
SELECT m.id, m.name
FROM majors m
JOIN university_majors um ON m.id = um.major_id
WHERE um.university_id = $1
ORDER BY m.name
`

func (q *Queries) GetUniversityMajors(ctx context.Context, universityID string) ([]Major, error) {
	rows, err := q.db.Query(ctx, getUniversityMajors, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Major{}
	for rows.Next() {
		var i Major
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniversitySpecialAffiliations = `-- name: GetUniversitySpecialAffiliations :many
SELECT sa.id, sa.name
FROM special_affiliations sa
JOIN university_special_affiliations usa ON sa.id = usa.special_affiliation_id
WHERE usa.university_id = $1
ORDER BY sa.name
`

func (q *Queries) GetUniversitySpecialAffiliations(ctx context.Context, universityID string) ([]SpecialAffiliation, error) {
	rows, err := q.db.Query(ctx, getUniversitySpecialAffiliations, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpecialAffiliation{}
	for rows.Next() {
		var i SpecialAffiliation
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniversityStudyFormats = `-- name: GetUniversityStudyFormats :many
SELECT sf.id, sf.name
FROM study_formats sf
JOIN university_study_formats usf ON sf.id = usf.study_format_id
WHERE usf.university_id = $1
ORDER BY sf.name
`

func (q *Queries) GetUniversityStudyFormats(ctx context.Context, universityID string) ([]StudyFormat, error) {
	rows, err := q.db.Query(ctx, getUniversityStudyFormats, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudyFormat{}
	for rows.Next() {
		var i StudyFormat
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniversitySupportServices = `-- name: GetUniversitySupportServices :many
SELECT ss.id, ss.name
FROM support_services ss
JOIN university_support_services uss ON ss.id = uss.support_service_id
WHERE uss.university_id = $1
ORDER BY ss.name
`

func (q *Queries) GetUniversitySupportServices(ctx context.Context, universityID string) ([]SupportService, error) {
	rows, err := q.db.Query(ctx, getUniversitySupportServices, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportService{}
	for rows.Next() {
		var i SupportService
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUniversityAthletics = `-- name: InsertUniversityAthletics :exec
INSERT INTO university_athletics (university_id, athletic_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (university_id, athletic_id) DO NOTHING
`

type InsertUniversityAthleticsParams struct {
	UniversityID string
	Column2      []string
}

func (q *Queries) InsertUniversityAthletics(ctx context.Context, arg InsertUniversityAthleticsParams) error {
	_, err := q.db.Exec(ctx, insertUniversityAthletics, arg.UniversityID, arg.Column2)
	return err
}

const insertUniversityDegreeLevels = `-- name: InsertUniversityDegreeLevels :exec
INSERT INTO university_degree_levels (university_id, degree_level_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (university_id, degree_level_id) DO NOTHING
`

type InsertUniversityDegreeLevelsParams struct {
	UniversityID string
	Column2      []string
}

func (q *Queries) InsertUniversityDegreeLevels(ctx context.Context, arg InsertUniversityDegreeLevelsParams) error {
	_, err := q.db.Exec(ctx, insertUniversityDegreeLevels, arg.UniversityID, arg.Column2)
	return err
}

const insertUniversityMajors = `-- name: InsertUniversityMajors :exec
INSERT INTO university_majors (university_id, major_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (university_id, major_id) DO NOTHING
`

type InsertUniversityMajorsParams struct {
	UniversityID string
	Column2      []string
}

func (q *Queries) InsertUniversityMajors(ctx context.Context, arg InsertUniversityMajorsParams) error {
	_, err := q.db.Exec(ctx, insertUniversityMajors, arg.UniversityID, arg.Column2)
	return err
}

const insertUniversitySpecialAffiliations = `-- name: InsertUniversitySpecialAffiliations :exec
INSERT INTO university_special_affiliations (university_id, special_affiliation_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (university_id, special_affiliation_id) DO NOTHING
`

type InsertUniversitySpecialAffiliationsParams struct {
	UniversityID string
	Column2      []string
}

func (q *Queries) InsertUniversitySpecialAffiliations(ctx context.Context, arg InsertUniversitySpecialAffiliationsParams) error {
	_, err := q.db.Exec(ctx, insertUniversitySpecialAffiliations, arg.UniversityID, arg.Column2)
	return err
}

const insertUniversityStudyFormats = `-- name: InsertUniversityStudyFormats :exec
INSERT INTO university_study_formats (university_id, study_format_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (university_id, study_format_id) DO NOTHING
`

type InsertUniversityStudyFormatsParams struct {
	UniversityID string
	Column2      []string
}

func (q *Queries) InsertUniversityStudyFormats(ctx context.Context, arg InsertUniversityStudyFormatsParams) error {
	_, err := q.db.Exec(ctx, insertUniversityStudyFormats, arg.UniversityID, arg.Column2)
	return err
}

const insertUniversitySupportServices = `-- name: InsertUniversitySupportServices :exec
INSERT INTO university_support_services (university_id, support_service_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (university_id, support_service_id) DO NOTHING
`

type InsertUniversitySupportServicesParams struct {
	UniversityID string
	Column2      []string
}

func (q *Queries) InsertUniversitySupportServices(ctx context.Context, arg InsertUniversitySupportServicesParams) error {
	_, err := q.db.Exec(ctx, insertUniversitySupportServices, arg.UniversityID, arg.Column2)
	return err
}

const listUniversities = `-- name: ListUniversities :many
SELECT id, name, slug, overview, excerpt, country, state, city, full_location, cover_image, logo, institution_type, campus_setting, in_state_tuition, out_of_state_tuition, international_tuition, need_based_aid, merit_scholarships, work_study, no_application_fee, acceptance_rate, testing_policy, sat_range, act_range, on_campus_housing, freshmen_required_on_campus, contact_email, contact_phone, website, zipcode, tuition_min, tuition_max, avg_high_school_gpa, founded_year, campus_size, gallery_images, is_popular, is_featured, created_at, updated_at FROM universities ORDER BY name LIMIT $1 OFFSET $2
`

type ListUniversitiesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUniversities(ctx context.Context, arg ListUniversitiesParams) ([]University, error) {
	rows, err := q.db.Query(ctx, listUniversities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []University{}
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Overview,
			&i.Excerpt,
			&i.Country,
			&i.State,
			&i.City,
			&i.FullLocation,
			&i.CoverImage,
			&i.Logo,
			&i.InstitutionType,
			&i.CampusSetting,
			&i.InStateTuition,
			&i.OutOfStateTuition,
			&i.InternationalTuition,
			&i.NeedBasedAid,
			&i.MeritScholarships,
			&i.WorkStudy,
			&i.NoApplicationFee,
			&i.AcceptanceRate,
			&i.TestingPolicy,
			&i.SatRange,
			&i.ActRange,
			&i.OnCampusHousing,
			&i.FreshmenRequiredOnCampus,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Website,
			&i.Zipcode,
			&i.TuitionMin,
			&i.TuitionMax,
			&i.AvgHighSchoolGpa,
			&i.FoundedYear,
			&i.CampusSize,
			&i.GalleryImages,
			&i.IsPopular,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUniversities = `-- name: SearchUniversities :many
SELECT
    id,
    name,
    slug,
    COALESCE(country, '') AS country,
    COALESCE(state, '') AS state,
    COALESCE(city, '') AS city,
    COALESCE(full_location, '') AS full_location,
    COALESCE(logo, '') AS logo
FROM universities
WHERE similarity(name, $1) > 0.2
   OR similarity(full_location, $1) > 0.2
   OR similarity(city, $1) > 0.2
   OR similarity(state, $1) > 0.2
   OR similarity(country, $1) > 0.2
ORDER BY GREATEST(
    similarity(name, $1),
    similarity(full_location, $1),
    similarity(city, $1)
) DESC, name ASC
LIMIT $2
`

type SearchUniversitiesParams struct {
	Similarity string
	Limit      int32
}

type SearchUniversitiesRow struct {
	ID           string
	Name         string
	Slug         string
	Country      string
	State        string
	City         string
	FullLocation string
	Logo         string
}

// Typo-tolerant search across name + location fields via pg_trgm similarity.
// Threshold 0.2 is below the PG default of 0.3, so "cambrige" still matches
// "Cambridge". Results are ranked by max similarity across the matched fields.
// COALESCE keeps nullable location/URL columns as plain strings in the row type
// (the API response does not carry nulls).
func (q *Queries) SearchUniversities(ctx context.Context, arg SearchUniversitiesParams) ([]SearchUniversitiesRow, error) {
	rows, err := q.db.Query(ctx, searchUniversities, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUniversitiesRow{}
	for rows.Next() {
		var i SearchUniversitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Country,
			&i.State,
			&i.City,
			&i.FullLocation,
			&i.Logo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
