// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, email, password, role)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, avatar, email, password, oauth_provider, oauth_id, email_verified, created_at, updated_at, role
`

type CreateUserParams struct {
	FullName string
	Email    string
	Password *string
	Role     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const createUserWithOAuth = `-- name: CreateUserWithOAuth :one
INSERT INTO users (full_name, email, oauth_provider, oauth_id, avatar, email_verified, role)
VALUES ($1, $2, $3, $4, $5, true, 'student')
RETURNING id, full_name, avatar, email, password, oauth_provider, oauth_id, email_verified, created_at, updated_at, role
`

type CreateUserWithOAuthParams struct {
	FullName   string
	Email      string
	Provider   *string
	ProviderID *string
	Avatar     *string
}

func (q *Queries) CreateUserWithOAuth(ctx context.Context, arg CreateUserWithOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithOAuth,
		arg.FullName,
		arg.Email,
		arg.Provider,
		arg.ProviderID,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, avatar, email, password, oauth_provider, oauth_id, email_verified, created_at, updated_at, role FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, avatar, email, password, oauth_provider, oauth_id, email_verified, created_at, updated_at, role FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, full_name, avatar, email, password, oauth_provider, oauth_id, email_verified, created_at, updated_at, role FROM users
WHERE oauth_provider = $1 AND oauth_id = $2
`

type GetUserByProviderParams struct {
	Provider   *string
	ProviderID *string
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProvider, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
