package claim

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"log"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"fmu-backend/internal/auth"
	"fmu-backend/internal/errs"
	"fmu-backend/internal/mail"
	"fmu-backend/internal/pagination"
	"fmu-backend/internal/user"
)

const (
	StatusPending  = "pending"
	StatusApproved = "approved"
	StatusRejected = "rejected"

	// plainPasswordBytes is what the autogenerated representative password
	// will be when an admin approves a claim. Long enough to satisfy the
	// user service's min=8 validator and short enough for the admin to
	// copy-paste into an email. Hex-encoded 8 random bytes → 16 chars.
	plainPasswordBytes = 8
)

// UniversityExister is the slim contract the claim service needs from
// university — just enough to confirm a university exists before accepting a
// claim against it. Errors should wrap errs.ErrNotFound on miss.
type UniversityExister interface {
	GetByID(ctx context.Context, id string) error
}

// CollegeExister is the slim contract for college existence checks.
type CollegeExister interface {
	GetByID(ctx context.Context, id string) error
}

// UserCreator is the slim contract for creating the representative account
// once a claim is approved. user.UserService satisfies it.
type UserCreator interface {
	CreateRepresentative(ctx context.Context, fullName, email, password, universityID string) (*user.User, error)
	CreateCollegeRepresentative(ctx context.Context, fullName, email, password, collegeID string) (*user.User, error)
}

type ClaimService interface {
	Submit(ctx context.Context, target ClaimTarget, targetID string, req *SubmitClaimRequest) (*SubmitClaimResponse, error)
	GetByID(ctx context.Context, id string) (*ClaimDetailResponse, error)
	List(ctx context.Context, target ClaimTarget, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error)
	Approve(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*ApproveClaimResponse, error)
	Reject(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*RejectClaimResponse, error)
}

type claimService struct {
	uniRepo    UniversityClaimRepository
	colRepo    CollegeClaimRepository
	university UniversityExister
	college    CollegeExister
	users      UserCreator
	mailer     *mail.Client // nil = approval emails disabled (SMTP not configured)
	loginURL   string
}

// NewClaimService wires the claim service against two repositories (one
// per target type) and two existers (for the existence pre-check on submit).
// Callers with concrete service handles should use
// NewUniversityExisterAdapter / NewCollegeExisterAdapter to bridge them.
//
// mailer is the SMTP client used to send the credentials email on
// approval. Pass nil when SMTP is not configured — approval still
// succeeds and returns the plaintext password to the admin, who can
// forward it manually. loginURL is the absolute URL of the frontend
// login page (e.g. "https://app.example.com/login") embedded in the
// approval email.
func NewClaimService(
	uniRepo UniversityClaimRepository,
	colRepo CollegeClaimRepository,
	university UniversityExister,
	college CollegeExister,
	users UserCreator,
	mailer *mail.Client,
	loginURL string,
) ClaimService {
	return &claimService{
		uniRepo:    uniRepo,
		colRepo:    colRepo,
		university: university,
		college:    college,
		users:      users,
		mailer:     mailer,
		loginURL:   loginURL,
	}
}

func (s *claimService) Submit(ctx context.Context, target ClaimTarget, targetID string, req *SubmitClaimRequest) (*SubmitClaimResponse, error) {
	// Role gate: students and admins cannot claim. Anonymous callers
	// (no claims in context) and any non-student, non-admin role pass
	// through. OptionalAuthMiddleware injects claims when a valid JWT
	// cookie is present, so this catches role-based abuse without
	// forcing anonymous visitors to register first.
	if claims, err := auth.ClaimsFromContext(ctx); err == nil {
		switch claims.Role {
		case auth.RoleStudent, auth.RoleAdmin:
			return nil, errs.ErrClaimRoleNotAllowed
		}
	}

	switch target {
	case TargetUniversity:
		if err := s.university.GetByID(ctx, targetID); err != nil {
			if errors.Is(err, errs.ErrNotFound) {
				return nil, errs.ErrNotFound
			}
			return nil, err
		}
		row, err := s.uniRepo.Create(ctx, targetID, strings.TrimSpace(req.FullName), strings.TrimSpace(req.WorkEmail), req.DocumentURL)
		if err != nil {
			log.Default().Printf("submit university claim: %v", err)
			return nil, err
		}
		return &SubmitClaimResponse{
			ClaimID:   row.ID,
			Type:      TargetUniversity,
			TargetID:  row.UniversityID,
			Status:    row.Status,
			CreatedAt: row.CreatedAt,
		}, nil

	case TargetCollege:
		if err := s.college.GetByID(ctx, targetID); err != nil {
			if errors.Is(err, errs.ErrNotFound) {
				return nil, errs.ErrNotFound
			}
			return nil, err
		}
		row, err := s.colRepo.Create(ctx, targetID, strings.TrimSpace(req.FullName), strings.TrimSpace(req.WorkEmail), req.DocumentURL)
		if err != nil {
			log.Default().Printf("submit college claim: %v", err)
			return nil, err
		}
		return &SubmitClaimResponse{
			ClaimID:   row.ID,
			Type:      TargetCollege,
			TargetID:  row.CollegeID,
			Status:    row.Status,
			CreatedAt: row.CreatedAt,
		}, nil

	default:
		return nil, errs.ErrBadRequest
	}
}

// findClaim looks up a claim id across both tables. Returns the row, the
// target type, and any error. Used by Approve/Reject/GetByID where the URL
// only carries the id.
func (s *claimService) findClaim(ctx context.Context, id string) (claimJoinRow, ClaimTarget, error) {
	uniRow, err := s.uniRepo.GetByID(ctx, id)
	if err == nil {
		return fromUniGetRow(uniRow), TargetUniversity, nil
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return claimJoinRow{}, "", err
	}

	colRow, err := s.colRepo.GetByID(ctx, id)
	if err == nil {
		return fromColGetRow(colRow), TargetCollege, nil
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return claimJoinRow{}, "", errs.ErrNotFound
	}
	return claimJoinRow{}, "", err
}

func (s *claimService) GetByID(ctx context.Context, id string) (*ClaimDetailResponse, error) {
	row, _, err := s.findClaim(ctx, id)
	if err != nil {
		if errors.Is(err, errs.ErrNotFound) {
			return nil, errs.ErrNotFound
		}
		log.Default().Printf("get claim %s: %v", id, err)
		return nil, err
	}
	return &ClaimDetailResponse{ClaimListItem: toClaimListItem(row)}, nil
}

func (s *claimService) List(ctx context.Context, target ClaimTarget, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error) {
	if statusFilter != "" && statusFilter != StatusPending && statusFilter != StatusApproved && statusFilter != StatusRejected {
		return nil, 0, errs.ErrBadRequest
	}

	switch target {
	case TargetUniversity:
		return s.listUniversity(ctx, statusFilter, q)
	case TargetCollege:
		return s.listCollege(ctx, statusFilter, q)
	case "":
		// No type filter — show both. Two queries merged into one paginated
		// feed; the global order is created_at DESC. Pagination becomes
		// approximate across the union but the moderation dashboard is
		// low-traffic and admins can refine with ?type=.
		return s.listBoth(ctx, statusFilter, q)
	default:
		return nil, 0, errs.ErrBadRequest
	}
}

func (s *claimService) listUniversity(ctx context.Context, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error) {
	total, err := s.uniRepo.Count(ctx, statusFilter)
	if err != nil {
		log.Default().Printf("count university claims: %v", err)
		return nil, 0, err
	}
	rows, err := s.uniRepo.List(ctx, statusFilter, int32(q.Limit()), int32(q.Offset()))
	if err != nil {
		log.Default().Printf("list university claims: %v", err)
		return nil, 0, err
	}
	items := make([]ClaimListItem, len(rows))
	for i, r := range rows {
		items[i] = toClaimListItem(fromUniListRow(r))
	}
	return items, total, nil
}

func (s *claimService) listCollege(ctx context.Context, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error) {
	total, err := s.colRepo.Count(ctx, statusFilter)
	if err != nil {
		log.Default().Printf("count college claims: %v", err)
		return nil, 0, err
	}
	rows, err := s.colRepo.List(ctx, statusFilter, int32(q.Limit()), int32(q.Offset()))
	if err != nil {
		log.Default().Printf("list college claims: %v", err)
		return nil, 0, err
	}
	items := make([]ClaimListItem, len(rows))
	for i, r := range rows {
		items[i] = toClaimListItem(fromColListRow(r))
	}
	return items, total, nil
}

func (s *claimService) listBoth(ctx context.Context, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error) {
	uniTotal, err := s.uniRepo.Count(ctx, statusFilter)
	if err != nil {
		log.Default().Printf("count university claims: %v", err)
		return nil, 0, err
	}
	colTotal, err := s.colRepo.Count(ctx, statusFilter)
	if err != nil {
		log.Default().Printf("count college claims: %v", err)
		return nil, 0, err
	}
	total := uniTotal + colTotal

	uniRows, err := s.uniRepo.List(ctx, statusFilter, int32(q.Limit()), int32(q.Offset()))
	if err != nil {
		log.Default().Printf("list university claims: %v", err)
		return nil, 0, err
	}
	colRows, err := s.colRepo.List(ctx, statusFilter, int32(q.Limit()), int32(q.Offset()))
	if err != nil {
		log.Default().Printf("list college claims: %v", err)
		return nil, 0, err
	}

	items := make([]ClaimListItem, 0, len(uniRows)+len(colRows))
	for _, r := range uniRows {
		items = append(items, toClaimListItem(fromUniListRow(r)))
	}
	for _, r := range colRows {
		items = append(items, toClaimListItem(fromColListRow(r)))
	}
	return items, total, nil
}

// Approve looks up the claim (across both tables), creates the representative
// user bound to the claim's target, then flips the claim to approved. If the
// user insert succeeds but the claim update fails, the representative exists
// with an orphaned claim; we surface the original claim error so the admin
// can retry (the UNIQUE constraint on representative_*_id prevents double
// allocation).
func (s *claimService) Approve(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*ApproveClaimResponse, error) {
	row, target, err := s.findClaim(ctx, claimID)
	if err != nil {
		if errors.Is(err, errs.ErrNotFound) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	if row.Status != StatusPending {
		return nil, errs.ErrClaimAlreadyReviewed
	}

	password, err := generatePassword()
	if err != nil {
		log.Default().Printf("generate password: %v", err)
		return nil, err
	}

	var (
		newUser    *user.User
		approveErr error
		reviewNote = stringPtrOrNil(req.ReviewNote)
	)

	switch target {
	case TargetUniversity:
		newUser, approveErr = s.users.CreateRepresentative(ctx, row.FullName, row.WorkEmail, password, row.TargetID)
		if approveErr == nil {
			if _, err := s.uniRepo.Approve(ctx, claimID, reviewerID, reviewNote, newUser.ID); err != nil {
				log.Default().Printf("approve university claim %s: %v", claimID, err)
				return nil, err
			}
		}
	case TargetCollege:
		newUser, approveErr = s.users.CreateCollegeRepresentative(ctx, row.FullName, row.WorkEmail, password, row.TargetID)
		if approveErr == nil {
			if _, err := s.colRepo.Approve(ctx, claimID, reviewerID, reviewNote, newUser.ID); err != nil {
				log.Default().Printf("approve college claim %s: %v", claimID, err)
				return nil, err
			}
		}
	default:
		return nil, errs.ErrBadRequest
	}

	if approveErr != nil {
		// UNIQUE on representative_*_id surfaces as 23505; map it.
		var pgErr *pgconn.PgError
		if errors.As(approveErr, &pgErr) && pgErr.Code == "23505" {
			switch target {
			case TargetUniversity:
				return nil, errs.ErrUniversityAlreadyHasRepresentative
			case TargetCollege:
				return nil, errs.ErrCollegeAlreadyHasRepresentative
			}
		}
		return nil, approveErr
	}

	// Refetch via the JOIN query so the response carries the target name
	// (UPDATE...RETURNING can't reach across to universities/colleges).
	updated, _, err := s.findClaim(ctx, claimID)
	if err != nil {
		log.Default().Printf("refetch approved claim %s: %v", claimID, err)
		return nil, err
	}

	// Email the new representative with their credentials. Best-effort:
	// when SMTP is unreachable the admin already received the plaintext
	// password in this response and can forward it manually, so we log
	// and continue rather than failing the approval.
	if s.mailer != nil {
		institutionType := "university"
		if target == TargetCollege {
			institutionType = "college"
		}
		if err := s.mailer.SendClaimApproved(ctx, mail.ClaimApprovedData{
			Email:           newUser.Email,
			Password:        password,
			FullName:        row.FullName,
			InstitutionType: institutionType,
			InstitutionName: updated.TargetName,
			LoginURL:        s.loginURL,
		}); err != nil {
			log.Default().Printf("claim approval: send credentials email: %v", err)
		}
	}

	return &ApproveClaimResponse{
		Claim:         toClaimListItem(updated),
		CreatedUserID: newUser.ID,
		Email:         newUser.Email,
		PlainPassword: password,
		Role:          auth.RoleRepresentative,
	}, nil
}

func (s *claimService) Reject(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*RejectClaimResponse, error) {
	row, target, err := s.findClaim(ctx, claimID)
	if err != nil {
		if errors.Is(err, errs.ErrNotFound) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	if row.Status != StatusPending {
		return nil, errs.ErrClaimAlreadyReviewed
	}

	reviewNote := stringPtrOrNil(req.ReviewNote)
	switch target {
	case TargetUniversity:
		if _, err := s.uniRepo.Reject(ctx, claimID, reviewerID, reviewNote); err != nil {
			log.Default().Printf("reject university claim %s: %v", claimID, err)
			return nil, err
		}
	case TargetCollege:
		if _, err := s.colRepo.Reject(ctx, claimID, reviewerID, reviewNote); err != nil {
			log.Default().Printf("reject college claim %s: %v", claimID, err)
			return nil, err
		}
	default:
		return nil, errs.ErrBadRequest
	}

	updated, _, err := s.findClaim(ctx, claimID)
	if err != nil {
		log.Default().Printf("refetch rejected claim %s: %v", claimID, err)
		return nil, err
	}
	return &RejectClaimResponse{Claim: toClaimListItem(updated)}, nil
}

// generatePassword returns a fresh hex-encoded random string suitable for the
// representative account. We hand the admin the plaintext once and never
// persist it in cleartext.
func generatePassword() (string, error) {
	buf := make([]byte, plainPasswordBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func stringPtrOrNil(s string) *string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	return &s
}
