package claim

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"log"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"fmu-backend/internal/auth"
	"fmu-backend/internal/errs"
	"fmu-backend/internal/pagination"
	"fmu-backend/internal/user"
)

const (
	StatusPending  = "pending"
	StatusApproved = "approved"
	StatusRejected = "rejected"

	// MinPasswordLength is what the autogenerated representative password will
	// be when an admin approves a claim. Long enough to satisfy the user
	// service's min=8 validator and short enough for the admin to copy-paste
	// into an email. Hex-encoded 8 random bytes → 16 chars.
	plainPasswordBytes = 8
)

// UniversityExister is the slim contract the claim service needs from
// university — just enough to confirm a university exists before accepting a
// claim against it. Errors should wrap errs.ErrNotFound on miss.
type UniversityExister interface {
	GetByID(ctx context.Context, id string) error
}

// UserCreator is the slim contract for creating the representative account
// once a claim is approved. user.UserService satisfies it.
type UserCreator interface {
	CreateRepresentative(ctx context.Context, fullName, email, password, universityID string) (*user.User, error)
}

type ClaimService interface {
	Submit(ctx context.Context, universityID string, req *SubmitClaimRequest) (*SubmitClaimResponse, error)
	GetByID(ctx context.Context, id string) (*ClaimDetailResponse, error)
	List(ctx context.Context, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error)
	Approve(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*ApproveClaimResponse, error)
	Reject(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*RejectClaimResponse, error)
}

type claimService struct {
	repo       ClaimRepository
	university UniversityExister
	users      UserCreator
}

// NewClaimService wires the claim service against an explicit UniversityExister.
// Callers that have a full university.UniversityService can use
// newUniversityExisterAdapter to bridge.
func NewClaimService(repo ClaimRepository, university UniversityExister, users UserCreator) ClaimService {
	return &claimService{
		repo:       repo,
		university: university,
		users:      users,
	}
}

func (s *claimService) Submit(ctx context.Context, universityID string, req *SubmitClaimRequest) (*SubmitClaimResponse, error) {
	// Role gate: students and admins cannot claim. Anonymous callers
	// (no claims in context) and any non-student, non-admin role pass
	// through. OptionalAuthMiddleware injects claims when a valid JWT
	// cookie is present, so this catches role-based abuse without
	// forcing anonymous visitors to register first.
	if claims, err := auth.ClaimsFromContext(ctx); err == nil {
		switch claims.Role {
		case auth.RoleStudent, auth.RoleAdmin:
			return nil, errs.ErrClaimRoleNotAllowed
		}
	}

	if err := s.university.GetByID(ctx, universityID); err != nil {
		if errors.Is(err, errs.ErrNotFound) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}

	row, err := s.repo.Create(ctx, universityID, req.FullName, strings.TrimSpace(req.WorkEmail), req.DocumentURL)
	if err != nil {
		log.Default().Printf("submit claim: %v", err)
		return nil, err
	}
	return &SubmitClaimResponse{
		ClaimID:      row.ID,
		UniversityID: row.UniversityID,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
	}, nil
}

func (s *claimService) GetByID(ctx context.Context, id string) (*ClaimDetailResponse, error) {
	row, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, errs.ErrNotFound
		}
		log.Default().Printf("get claim %s: %v", id, err)
		return nil, err
	}
	item := toClaimListItem(fromGetRow(row))
	return &ClaimDetailResponse{ClaimListItem: item}, nil
}

func (s *claimService) List(ctx context.Context, statusFilter string, q pagination.Query) ([]ClaimListItem, int64, error) {
	if statusFilter != "" && statusFilter != StatusPending && statusFilter != StatusApproved && statusFilter != StatusRejected {
		return nil, 0, errs.ErrBadRequest
	}

	total, err := s.repo.Count(ctx, statusFilter)
	if err != nil {
		log.Default().Printf("count claims: %v", err)
		return nil, 0, err
	}

	rows, err := s.repo.List(ctx, statusFilter, int32(q.Limit()), int32(q.Offset()))
	if err != nil {
		log.Default().Printf("list claims: %v", err)
		return nil, 0, err
	}

	items := make([]ClaimListItem, len(rows))
	for i, r := range rows {
		items[i] = toClaimListItem(fromListRow(r))
	}
	return items, total, nil
}

// Approve creates the representative user, then flips the claim to approved.
// If the user insert succeeds but the claim update fails the representative
// exists with an orphaned claim; we surface the original claim error so the
// admin can retry (the UNIQUE constraint on representative_university_id
// prevents double-allocation if they retry).
func (s *claimService) Approve(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*ApproveClaimResponse, error) {
	claim, err := s.repo.GetByID(ctx, claimID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	if claim.Status != StatusPending {
		return nil, errs.ErrClaimAlreadyReviewed
	}

	password, err := generatePassword()
	if err != nil {
		log.Default().Printf("generate password: %v", err)
		return nil, err
	}

	newUser, err := s.users.CreateRepresentative(ctx, claim.FullName, claim.WorkEmail, password, claim.UniversityID)
	if err != nil {
		// The UNIQUE constraint on representative_university_id surfaces as
		// 23505; map it to a clear 409.
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return nil, errs.ErrUniversityAlreadyHasRepresentative
		}
		log.Default().Printf("create representative for claim %s: %v", claimID, err)
		return nil, err
	}

	if _, err := s.repo.Approve(ctx, claimID, reviewerID, stringPtrOrNil(req.ReviewNote), newUser.ID); err != nil {
		log.Default().Printf("approve claim %s: %v", claimID, err)
		return nil, err
	}

	// Refetch via the JOIN query so the response carries the university
	// name (UPDATE...RETURNING can't reach across to universities).
	updated, err := s.repo.GetByID(ctx, claimID)
	if err != nil {
		log.Default().Printf("refetch approved claim %s: %v", claimID, err)
		return nil, err
	}

	return &ApproveClaimResponse{
		Claim:         toClaimListItem(fromGetRow(updated)),
		CreatedUserID: newUser.ID,
		Email:         newUser.Email,
		PlainPassword: password,
		Role:          auth.RoleRepresentative,
	}, nil
}

func (s *claimService) Reject(ctx context.Context, claimID, reviewerID string, req *ReviewDecisionRequest) (*RejectClaimResponse, error) {
	claim, err := s.repo.GetByID(ctx, claimID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, errs.ErrNotFound
		}
		return nil, err
	}
	if claim.Status != StatusPending {
		return nil, errs.ErrClaimAlreadyReviewed
	}

	if _, err := s.repo.Reject(ctx, claimID, reviewerID, stringPtrOrNil(req.ReviewNote)); err != nil {
		log.Default().Printf("reject claim %s: %v", claimID, err)
		return nil, err
	}
	updated, err := s.repo.GetByID(ctx, claimID)
	if err != nil {
		log.Default().Printf("refetch rejected claim %s: %v", claimID, err)
		return nil, err
	}
	return &RejectClaimResponse{Claim: toClaimListItem(fromGetRow(updated))}, nil
}

// generatePassword returns a fresh hex-encoded random string suitable for the
// representative account. We hand the admin the plaintext once and never
// persist it in cleartext.
func generatePassword() (string, error) {
	buf := make([]byte, plainPasswordBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func stringPtrOrNil(s string) *string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	return &s
}
